name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Tests
      run: xcodebuild -scheme AlgorithmPractiseTests test | xcpretty
